#### About
Reading point cloud data, mesh and saving them.
* Github - https://github.com/isl-org/Open3D
1. Point clouds are collection of points in 3D space that may or maynot represent an object.
2. Point clouds are generated using 3D sensors.
3. Meshes are structures generated from point clouds by triangulation methods.
4. Various format of point cloud include 
* xyz where each line contains x,y,z 3D coordinates
* xyzn where each line contains x,y,x,nx,ny,nz i.e 3D coordinates and their normals
* xyzrgb where each line contains x,y,z,r,g,b i.e 3D coordinates and RGB normalised.
* pts where first line is an integer representing number of points
* pcd is point cloud data
* ply is polygon format
5. Various format of mesh file format includes
* ply - polygon file format which contains both point cloud and mesh data
* obj - object files
* off, stl, gltf etc 

6. Voxel is a cube in 3D space.



In [14]:
import open3d as o3d
import numpy as np

In [11]:
point_cloud = o3d.io.read_point_cloud('flower_pot.pcd')
print(point_cloud)
o3d.visualization.draw_geometries([point_cloud])

geometry::PointCloud with 2048 points.


In [3]:
mesh = o3d.io.read_triangle_mesh('apple.ply')
mesh.compute_vertex_normals()

geometry::TriangleMesh with 650 points and 1236 triangles.

In [4]:
pcd = mesh.sample_points_uniformly(number_of_points=650)
o3d.visualization.draw_geometries([pcd])

#### Voxel downsampling
1. It's similar to max pooling and is a common preprocessing step.
2. It takes the point cloud and downsample

In [9]:
downsampled_pcd = pcd.voxel_down_sample(voxel_size=0.01)
o3d.visualization.draw_geometries([downsampled_pcd])

In [10]:
#drawing bounding box
downsampled_pcd_bbox = downsampled_pcd.get_oriented_bounding_box()
o3d.visualization.draw_geometries([downsampled_pcd,downsampled_pcd_bbox])

Similarly, We can crop a point cloud, color it etc
* Let's have a look at meshes's vertices and triangles

In [15]:
print(np.asarray(mesh.vertices))

[[ 3.54531e-02  6.25133e-03  4.26838e-03]
 [ 3.60000e-02  1.21484e-09  4.26838e-03]
 [ 3.38289e-02  1.23128e-02  4.26838e-03]
 ...
 [ 2.31823e-03 -6.21136e-04  6.90684e-02]
 [ 3.70917e-03 -9.93818e-04  7.62684e-02]
 [ 0.00000e+00 -1.86943e-09  7.48284e-02]]


In [16]:
np.asarray(mesh.triangles)

array([[  0,  36,  37],
       [  0,  37,   1],
       [  2,  38,  36],
       ...,
       [649, 642, 645],
       [649, 645, 648],
       [649, 648, 582]], dtype=int32)

In [18]:
mesh.has_vertex_normals()


True

In [19]:
o3d.visualization.draw_geometries([mesh])

In [20]:
#computing vertex normals
mesh.compute_vertex_normals()

geometry::TriangleMesh with 650 points and 1236 triangles.

In [21]:
np.asarray(mesh.triangle_normals)

array([[ 0.75404393,  0.06596792, -0.65350285],
       [ 0.7540439 ,  0.06596783, -0.6535029 ],
       [ 0.73113148,  0.19591158, -0.65350242],
       ...,
       [-0.28067166,  0.21536159,  0.93533032],
       [-0.32684726,  0.13538084,  0.93533037],
       [-0.35074894,  0.04617402,  0.9353305 ]])

In [27]:
#painting a mesh #normalised RGB
mesh.paint_uniform_color([0.2,0.2,1.0])
o3d.visualization.draw_geometries([mesh])


In [24]:
#cropping a mesh
mesh.triangles = o3d.utility.Vector3iVector(
    np.asarray(mesh.triangles)[:len(mesh.triangles)//2,:]
)
mesh.triangle_normals = o3d.utility.Vector3dVector(
    np.asarray(mesh.triangle_normals)[:len(mesh.triangle_normals)//2,:]

)
np.asarray(mesh.triangles)


array([[  0,  36,  37],
       [  0,  37,   1],
       [  2,  38,  36],
       [  2,  36,   0],
       [  3,  39,  38],
       [  3,  38,   2],
       [  4,  40,  39],
       [  4,  39,   3],
       [  5,  41,  40],
       [  5,  40,   4],
       [  6,  42,  41],
       [  6,  41,   5],
       [  7,  43,  42],
       [  7,  42,   6],
       [  8,  44,  43],
       [  8,  43,   7],
       [  9,  45,  44],
       [  9,  44,   8],
       [ 10,  46,  45],
       [ 10,  45,   9],
       [ 11,  47,  46],
       [ 11,  46,  10],
       [ 12,  48,  47],
       [ 12,  47,  11],
       [ 13,  49,  48],
       [ 13,  48,  12],
       [ 14,  50,  49],
       [ 14,  49,  13],
       [ 15,  51,  50],
       [ 15,  50,  14],
       [ 16,  52,  51],
       [ 16,  51,  15],
       [ 17,  53,  52],
       [ 17,  52,  16],
       [ 18,  54,  53],
       [ 18,  53,  17],
       [ 19,  55,  54],
       [ 19,  54,  18],
       [ 20,  56,  55],
       [ 20,  55,  19],
       [ 21,  57,  56],
       [ 21,  56

In [25]:
o3d.visualization.draw_geometries([mesh])