##### About
Tokenization is one of the first steps of data processing when it comes to working with data in the domain of NLP.

* We will use spacy to tokenize input sentences and compare it's results with basic tokenization performed via Python.


#### Requirements
```
pip install spacy
python -m spacy download en_core_web_sm
```

In [1]:
# tokenization of a text using python
doc = "Hi, There ! This is a notebook on Tokenization"
for i,token in enumerate(doc.split(" ")):
    print("Token {} - {}".format(i,token))

Token 0 - Hi,
Token 1 - There
Token 2 - !
Token 3 - This
Token 4 - is
Token 5 - a
Token 6 - notebook
Token 7 - on
Token 8 - Tokenization


But, This straightforward approach of tokenisation encounters a lot of loopholes as text contains tokens which are noisy. Like associated with hyphens or name of various nouns.

* BERT uses the concept of sub-word tokens to permute over various combinations of characters which can form part of the vocabulary. It helps it in narrowing down to the OOV(Out of vocabulary) tokens.

Thus, We use spacy as an efficient tokenizer for NLP.

In [1]:
import spacy
nlp = spacy.load("en_core_web_sm")

#tokenizigng
doc = nlp("Hi, There ! This is a notebook on Tokenization")
for token in doc:
    print("Token: {}".format(token))

/home/suraj/anaconda3/envs/dl/lib/python3.7/site-packages/torch/cuda/__init__.py:80: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:112.)
  return torch._C._cuda_getDeviceCount() > 0
2023-01-15 01:21:26.881653: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2023-01-15 01:21:29.320432: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2023-01-15 01:21:29.322004: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2023-01-15 01:21:29.32

Token: Hi
Token: ,
Token: There
Token: !
Token: This
Token: is
Token: a
Token: notebook
Token: on
Token: Tokenization


One can also add his own tokenizer rules. Visit  <a href="https://spacy.io/usage/linguistic-features#special-cases"> Link </a>

Besides this, Each model like BERT, BART and its variants come with their own tokenizers. Let's have a look at one such variant.

In [4]:
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
    "Hi, This is our first Tokenizer Notebook",
    "Glad to see you here.",
    "What are you upto ?"
]

In [5]:
tokenizer = Tokenizer(num_words=20)
tokenizer.fit_on_texts(sentences)
word_idx = tokenizer.word_index
print(word_idx)

{'you': 1, 'hi': 2, 'this': 3, 'is': 4, 'our': 5, 'first': 6, 'tokenizer': 7, 'notebook': 8, 'glad': 9, 'to': 10, 'see': 11, 'here': 12, 'what': 13, 'are': 14, 'upto': 15}


In [6]:
# converting each tokenized sentence into sequence
sequences = tokenizer.texts_to_sequences(sentences)
for seq in sequences:
    print(seq) 

[2, 3, 4, 5, 6, 7, 8]
[9, 10, 11, 1, 12]
[13, 14, 1, 15]


In [8]:
# to ensure that each sequence contains same number of tokens which are a primary need for any NN. We'll pad
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_sequences = pad_sequences(sequences, padding='post')
for seq in padded_sequences:
    print(seq)

[2 3 4 5 6 7 8]
[ 9 10 11  1 12  0  0]
[13 14  1 15  0  0  0]


Tokenizer also comes as various types, Few of which are listed below
1. Word piece tokenizer of BERT, DistilBERT, Electra
2. Byte pair encoding tokenizer for GPT2.
3. Unigram.
4. Sentence piece(https://github.com/google/sentencepiece)