#### About
Tracking using Kalman filter in OpenCV.

> About the Algorithm.
1. It is used to estimate the position of a moving object across temporal dimension.
2. Gaussian curves are used to depict the positional estimate of a moving object.
3. Optimal estimate is often derived via mean and variance of Measurement estimate and State Estimate using Kalman Filter.
4. Initially, Kalman gain is found our via State estimate error and measurement error by using the formula k_g = E_st/(E_st+ E_ma) where E_ma and E_st are measurement and state estimate error of the gaussian curves.
5. Estimate at any time t is given by the following equation
> Est_t = Est_t-1 + KG(Ms - Est_t-1)
> where Est_x is estimate at time x, KG is kalman gain, Ms os measured_value
6. New state estimate error is then being calculated by following
> error_Est_t = (1-KG)(error_Est_t-1)

In [5]:
#kalman filter class
import numpy as np
import cv2

In [7]:
kf = cv2.KalmanFilter(2,10)
predict = kf.predict()
#initial prediction must be 0,0 since nothing was fed
print(predict)

[[0.]
 [0.]]


In [24]:
# kalman filter class for N 2D points

'''Kalman filtering for selected points in an image using OpenCV cv2.kalmanFilter class in Python '''
class Kalman_Filtering:

    def __init__(self):
        self.kf = cv2.KalmanFilter(4,2)

    def initialize(self):

       


        print('TRANSITION Matrix:')
        print(kalman.transitionMatrix)

        print('MEASUREMENT Matrix:')
        print(kalman.measurementMatrix)



    def predict(self,points):

        pred = []
        input_points = np.float32(np.ndarray.flatten(points))
        #print(input_points)
        #Correction Step
        self.kalman.correct(input_points)
        #Prediction step
        tp = self.kalman.predict()

        for i in self.Measurement_array:
            pred.append(int(tp[i]))

        return pred

In [25]:
kf = Kalman_Filtering(2)
kf.initialize()
points = [[ 10. , 20.],
 [ 20. , 20.],
 [ 30.,  20.],
 [ 40. , 20.],
 [ 50. , 20.],
 [ 60. , 20.]]

for point in points:
    predict = kf.predict((point[0],point[1]))
    print(predict)

[2, 3, 6, 7]
[0, 1, 4, 5]
TRANSITION Matrix:
[[1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
MEASUREMENT Matrix:
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]


TypeError: descriptor 'flatten' for 'numpy.ndarray' objects doesn't apply to a 'tuple' object